# 0 = No Summary; 1 = At very begining
APPROXIMATION_CONTEXT = 0
GIVE_FORMAT_EXAMPLES = 0
GIVE_LOOP_PERF_EXMAPLES = 0
PRINT_LLM_CONVO = 1
ERROR_BOUND = 0.50
REVERSED_PDG = 0
TEXT_PLANING = 1
# API_NAME = 'OpenAI'
API_NAME = 'Anthropic'
DEBUG = 0
